services:
  db:
    image: postgres:16.3
    container_name: url_shortener_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: url_shortener_db
      POSTGRES_PASSWORD: url_shortener_db
      POSTGRES_DB: url_shortener_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U url_shortener_db"]
      interval: 1s
      timeout: 3s
      retries: 5

  app:
    container_name: url_shortener_backend_app
    image: python:3.12-slim
    working_dir: /app
    env_file:
      - .env
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
